"""Initial migration5

Revision ID: 6d85d5803a19
Revises: 5b8709597255
Create Date: 2025-03-10 20:57:19.690628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d85d5803a19'
down_revision = '5b8709597255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
