"""Initial migration6

Revision ID: a0b111f6d91a
Revises: 6d85d5803a19
Create Date: 2025-03-10 23:51:53.971255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b111f6d91a'
down_revision = '6d85d5803a19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
